"use client";
import { costTotals, effectiveEventMileage } from "./domain";
import { fleetLocale, tr } from "./i18n";
import type { VehicleDetail } from "./types";
const escape = (v: unknown) => String(v ?? "—").replace(/[&<>"']/g, c => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;", "'":"&#39;" }[c]!));
export function printVehicle(detail: VehicleDetail, lang: string): boolean {
  const tab=window.open("", "_blank", "width=1100,height=850"); if(!tab)return false; tab.opener=null;
  const v=detail.vehicle.data; const label=(s:string)=>escape(tr(lang,s));
  const html=`<!doctype html><html lang="${escape(lang)}"><head><meta charset="utf-8"><title>${escape(v.plate)} — ACC BAU</title><style>
  body{font:12px system-ui,sans-serif;color:#222;margin:30px;line-height:1.5}h1{font-size:26px;margin:5px 0}h2{margin-top:24px;font-size:17px}header{border-bottom:3px solid #333;padding-bottom:14px}.meta{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.meta div{background:#f4f4f4;padding:8px}small{color:#555}table{border-collapse:collapse;width:100%;font-size:11px}th,td{border-bottom:1px solid #ddd;padding:7px;text-align:left;vertical-align:top;white-space:pre-line;overflow-wrap:anywhere}tr{break-inside:avoid}th{background:#eee}.note{white-space:pre-wrap}button{padding:10px}@media print{button{display:none}body{margin:0}thead{display:table-header-group}}@page{size:A4;margin:15mm}
  </style></head><body><button onclick="window.print()">${label("print")}</button><header><small>ACC BAU • ${label("overview")}</small><h1>${escape(v.plate)} — ${escape(v.make)} ${escape(v.model)}</h1><span>${escape(v.vin||"—")} • ${escape(new Date().toLocaleString(fleetLocale(lang)))}</span></header>
  <h2>${label("basic")}</h2><div class="meta">${[["driver",v.driver],["mileage",v.mileage==null?"—":`${v.mileage.toLocaleString(fleetLocale(lang))} km`],["mileageDate",v.mileageDate],["status",tr(lang,v.status)],["project",v.project],["location",v.location],["company",v.company],["year",v.year],["category",tr(lang,v.category)]].map(([k,x])=>`<div><small>${label(String(k))}</small><br><b>${escape(x||"—")}</b></div>`).join("")}</div>
  <p class="note">${escape(v.notes)}</p><h2>${label("plans")}</h2><p>${label("firstDue")}</p><table><thead><tr><th>${label("label")}</th><th>${label("dueDate")}</th><th>${label("dueMileage")}</th><th>${label("lastDone")}</th></tr></thead><tbody>${v.plans.filter(p=>!p.archived).map(p=>`<tr><td>${escape(p.label)}</td><td>${escape(p.dueDate||"—")}</td><td>${escape(p.dueMileage??"—")}</td><td>${escape(p.lastDoneDate||"—")}</td></tr>`).join("")}</tbody></table>
  <h2>${label("costSummary")}</h2><p>${Object.entries(costTotals(detail.events)).map(([key,total])=>`${escape(total.toFixed(2))} ${escape(key)}`).join(" • ")||"—"}</p><small>${label("costHint")}</small>
  <h2>${label("history")}</h2><table><thead><tr><th>${label("date")}</th><th>${label("kind")}</th><th>${label("titleField")}</th><th>${label("mileage")}</th><th>${label("by")}</th></tr></thead><tbody>${detail.events.map(e=>`<tr><td>${escape(e.happened_on)}</td><td>${label(e.kind)}</td><td>${escape(e.data.title)}\n${escape(e.data.notes)}${e.data.from||e.data.to?`\n${escape(e.data.from||"—")} → ${escape(e.data.to||"—")}`:""}${e.data.reason?`\n${escape(e.data.reason)}`:""}${e.kind==="mileage_correction"?`\n${escape(e.data.correctedId)} → ${escape(e.data.correctedMileage)} km`:""}</td><td>${escape(effectiveEventMileage(e,detail.events)??"—")}</td><td>${escape(e.created_by)}</td></tr>`).join("")}</tbody></table><p><small>${label("retained")}</small></p></body></html>`;
  tab.document.open();tab.document.write(html);tab.document.close();return true;
}
