import { costTotals, fmtDate, fmtNumber, planDue } from "./logic";
import type { Event, Vehicle } from "./schema";
const escape = (value: unknown) => String(value ?? "—").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;").replaceAll("'", "&#39;");
export function printVehicle(vehicle: Vehicle, events: Event[], admin: boolean): void {
  const w = window.open("", "_blank");
  if (!w) throw new Error("Przeglądarka zablokowała okno wydruku. Zezwól na otwieranie okien dla tej strony.");
  // No unescaped user input is ever inserted into a print document.
  const plans = vehicle.plans.map((p) => `<tr><td>${escape(p.title)}</td><td>${escape(p.disabled ? p.disabledReason : fmtDate(p.dueDate))}</td><td>${escape(fmtNumber(p.dueKm))}</td><td>${escape(fmtNumber(p.dueHours, 1))}</td><td>${escape({ due: "Termin osiągnięty / przekroczony", soon: "Zbliża się", missing: "Brak danych", ok: "W porządku", disabled: "Nie dotyczy" }[planDue(p, vehicle).level])}</td></tr>`).join("");
  const history = events.slice(0, 30).map((e) => `<tr><td>${escape(fmtDate(e.occurredOn))}</td><td>${escape(e.title)}${e.voidedAt ? " (UNIEWAŻNIONY)" : ""}</td><td>${escape(e.actorName)}</td><td>${escape(e.note)}</td></tr>`).join("");
  const totals = admin ? Object.entries(costTotals(events)).map(([c, n]) => `${escape(fmtNumber(n, 2))} ${escape(c)} brutto`).join(" • ") || "Brak zapisanych kosztów" : "Dostępne administratorowi";
  w.document.write(`<!DOCTYPE html><html lang="pl"><head><meta charset="utf-8"><title>Karta pojazdu ${escape(vehicle.registration || vehicle.fleetNumber)}</title><style>body{font:12px Arial,sans-serif;color:#111;margin:28px}h1{font-size:24px;margin-bottom:5px}h2{font-size:17px;margin-top:24px}p{line-height:1.6}table{width:100%;border-collapse:collapse}th,td{border:1px solid #bbb;padding:7px;text-align:left;vertical-align:top;white-space:pre-line}th{background:#eee}tr{break-inside:avoid}.note{font-size:10px;color:#555}@page{size:A4;margin:12mm}</style></head><body><h1>ACC BAU • Karta pojazdu</h1><p>${escape(vehicle.registration || vehicle.fleetNumber)} — ${escape(vehicle.make)} ${escape(vehicle.model)}<br>Numer flotowy: ${escape(vehicle.fleetNumber)} • VIN: ${escape(vehicle.vin)}<br>Firma: ${escape(vehicle.company)} • Użytkownik: ${escape(vehicle.driverName || "bez użytkownika")}<br>Budowa: ${escape(vehicle.site)} • Lokalizacja: ${escape(vehicle.location)}<br>Licznik: ${escape(fmtNumber(vehicle.mileage))} km (${escape(fmtDate(vehicle.mileageDate))}) • ${escape(fmtNumber(vehicle.hours, 1))} h (${escape(fmtDate(vehicle.hoursDate))})</p><p class="note">Wydruk: ${escape(new Date().toLocaleString("pl-PL"))}. Zestawienie danych wpisanych do aplikacji; nie zastępuje dokumentów pojazdu ani potwierdzenia dopuszczenia do użytkowania.</p><h2>Terminy i czynności</h2><table><thead><tr><th>Czynność</th><th>Data</th><th>km</th><th>h</th><th>Alarm</th></tr></thead><tbody>${plans}</tbody></table><h2>Koszty — wszystkie zapisane wpisy</h2><p>${totals}</p><h2>Ostatnie ${Math.min(events.length, 30)} wpisów historii</h2><table><thead><tr><th>Data</th><th>Wpis</th><th>Autor</th><th>Opis</th></tr></thead><tbody>${history}</tbody></table><p class="note">Pełna historia i załączniki są dostępne w aplikacji. Pełną historię można wyeksportować do CSV.</p></body></html>`);
  w.document.close(); w.opener = null; w.focus(); setTimeout(() => w.print(), 250);
}
