const test=require('node:test'),A=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),ts=require('typescript');
const {mergeLegacyRecord,LegacyConflict,legacyDateValue,sortLegacyHistory,safeCacheSet}=require('../lib/legacy-safety.ts');
const root=path.resolve(__dirname,'..'), source=fs.readFileSync(path.join(root,'app/page.tsx'),'utf8');
const ppe=[{id:'ppe1',employee:'Jan',name:'Kask',history:[{id:'hist1',note:'wydano'}],attachments:[{data:'data:image/jpeg;base64,ORIGINAL'}]}];
test('ustawienia ogólne zachowują PPE i nieznane pola z serwera',()=>{const base={people:['A'],ppeRecords:ppe,custom:{foo:1}};const next={...base,people:['A','B']};const current={...base,remoteOnly:'keep',ppeRecords:[...ppe,{id:'ppe2',name:'Szelki'}]};const r=mergeLegacyRecord(base,next,current);A.equal(r.ppeRecords.length,2);A.equal(r.remoteOnly,'keep');A.deepEqual(r.ppeRecords[0],ppe[0]);});
test('równoczesne dopisanie dwóch PPE nie gubi żadnego',()=>{const base={ppeRecords:ppe};const r=mergeLegacyRecord(base,{ppeRecords:[...ppe,{id:'ppeA'}]},{ppeRecords:[...ppe,{id:'ppeB'}]});A.deepEqual(r.ppeRecords.map(x=>x.id),['ppe1','ppeB','ppeA']);});
test('pominięcie PPE w tablicy nie usuwa rekordu',()=>A.deepEqual(mergeLegacyRecord({ppeRecords:ppe},{ppeRecords:[]},{ppeRecords:ppe}).ppeRecords,ppe));
test('niezależne zmiany pól jednego PPE są łączone',()=>{const base={ppeRecords:ppe};const next={ppeRecords:[{...ppe[0],name:'Kask poprawiony'}]};const remote={ppeRecords:[{...ppe[0],location:'Baza'}]};const r=mergeLegacyRecord(base,next,remote);A.equal(r.ppeRecords[0].location,'Baza');A.equal(r.ppeRecords[0].name,'Kask poprawiony');A.deepEqual(r.ppeRecords[0].attachments,ppe[0].attachments);});
test('konflikt tego samego pola blokuje zapis',()=>A.throws(()=>mergeLegacyRecord({name:'A'},{name:'B'},{name:'C'}),LegacyConflict));
test('ID duplikatu nie nadpisuje nowego wpisu z innego komputera',()=>A.throws(()=>mergeLegacyRecord({ppeRecords:[]},{ppeRecords:[{id:'x',name:'A'}]},{ppeRecords:[{id:'x',name:'B'}]}),LegacyConflict));
test('archiwizacja zachowuje historię i zdjęcia PPE',()=>{const r=mergeLegacyRecord({ppeRecords:ppe},{ppeRecords:[{...ppe[0],archived:true}]},{ppeRecords:ppe});A.equal(r.ppeRecords[0].archived,true);A.deepEqual(r.ppeRecords[0].history,ppe[0].history);A.deepEqual(r.ppeRecords[0].attachments,ppe[0].attachments);});
test('przeglądy narzędzia zachowane nawet przy pominięciu starszej pozycji',()=>{const old={inspections:[{id:'i1',attachments:['PHOTO']},{id:'i2'}]};const r=mergeLegacyRecord(old,{inspections:[{id:'i2'}]},old);A.deepEqual(r,old);});
test('historia bez identyfikatorów jest łączona, nie kasowana',()=>A.equal(mergeLegacyRecord({history:[{a:1}]},{history:[{a:2}]},{history:[{a:1},{a:3}]}).history.length,3));
test('polskie daty sortowane chronologicznie',()=>A.deepEqual(sortLegacyHistory([{date:'01.10.2026, 08:10:00'},{date:'30.09.2026, 19:00:00'},{date:'01.01.2025'}]).map(x=>x.date),['01.10.2026, 08:10:00','30.09.2026, 19:00:00','01.01.2025']));
test('polska data z czasem rozpoznawana',()=>A.ok(legacyDateValue('17.09.2026, 12:30:02')>legacyDateValue('17.09.2026, 12:30:01')));
test('błąd localStorage nie usuwa poprzedniej kopii',()=>{let removed=false;global.localStorage={setItem(){throw new Error('quota');},removeItem(){removed=true;}};A.equal(safeCacheSet('key',{a:1}),false);A.equal(removed,false);delete global.localStorage;});
// Execute the actual save() function extracted from SettingsModal, not a duplicate implementation.
function settingsSaveContext(fail=false){const sf=ts.createSourceFile('page.tsx',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);const modal=sf.statements.find(n=>ts.isFunctionDeclaration(n)&&n.name?.text==='SettingsModal');const save=modal.body.statements.find(n=>ts.isFunctionDeclaration(n)&&n.name?.text==='save');const ctx={saving:false,setSaving(){},pins:'A:secret',roles:'A:admin',people:'A\nB',projects:'P',categories:'K',settings:{people:['A'],ppeRecords:ppe,unknown:'retained'},clean:s=>s.split('\n').filter(Boolean),normalizeSettings:x=>x,setSettings(){},onClose(){ctx.closed=true;},alert(){ctx.alerted=true;},console:{error(){}},persistSettingsEverywhere:async(n,cb,base)=>{if(fail)throw Error('NETWORK');ctx.saved=n;ctx.base=base;}};vm.createContext(ctx);vm.runInContext(save.getText(sf)+'\nthis.run=save;',ctx);return ctx;}
test('REGRESJA: rzeczywisty save SettingsModal przekazuje całe PPE',async()=>{const c=settingsSaveContext();await c.run();A.equal(c.saved.ppeRecords.length,1);A.equal(c.saved.unknown,'retained');A.equal(c.base,c.settings);A.equal(c.closed,true);});
test('REGRESJA: błąd bazy nie zamyka SettingsModal',async()=>{const c=settingsSaveContext(true);await c.run();A.equal(c.closed,undefined);A.equal(c.alerted,true);});
test('kod aplikacji nie ma wywołania DELETE Supabase',()=>A.doesNotMatch(source,/\.delete\s*\(/));
test('kod nie czyści pamięci narzędzi i historii',()=>{A.doesNotMatch(source,/removeItem\((?:STORAGE_KEY|HISTORY_KEY|SETTINGS_KEY)\)/);});
test('legacy zapis sprawdza ten sam stan JSON przed zapisem',()=>A.ok(source.includes('.eq("data", JSON.stringify(row.data))')));
test('migracja nie modyfikuje istniejących tabel Tools/PPE',()=>{const sql=fs.readFileSync(path.join(root,'supabase/migrations/202609170001_acc_fleet_additive.sql'),'utf8');A.doesNotMatch(sql,/(?:insert\s+into|update|delete\s+from|drop\s+table|alter\s+table|truncate(?:\s+table)?)\s+(?:public\.)?(?:tools|history|settings)\b/i);A.doesNotMatch(sql,/\b(?:drop\s+table|truncate)\b/i);A.match(sql,/before update or delete on public\.%I/);A.match(sql,/bucket_id <> 'acc-fleet-private-v1'/);});
test('wydruk pojazdu escapuje HTML wpisany przez użytkownika',()=>{let html='';global.window={open:()=>({opener:null,document:{open(){},write(s){html=s;},close(){}}})};const {printVehicle}=require('../lib/fleet/print.ts'),{emptyVehicle}=require('../lib/fleet/domain.ts');const v={id:'test',data:{...emptyVehicle(),plate:'TEST',make:'Test',model:'<img src=x onerror=alert(1)>',notes:'<script>alert(2)</script>'},version:1,created_at:'',updated_at:''};A.equal(printVehicle({vehicle:v,events:[],files:[]},'pl'),true);A.ok(!html.includes('<script>alert'));A.ok(html.includes('&lt;script&gt;'));A.ok(!html.includes('<img src=x'));delete global.window;});
test('pierwszy zapis cache zachowuje dokładny oryginał sprzed aktualizacji',()=>{const map=new Map([['acc_settings_v7','{"ppeRecords":[{"id":"KEEP"}]}']]);global.localStorage={getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v)};A.equal(safeCacheSet('acc_settings_v7',{ppeRecords:[]}),true);A.equal(map.get('acc_settings_v7__before_fleet_v1'),'{"ppeRecords":[{"id":"KEEP"}]}');safeCacheSet('acc_settings_v7',{newer:true});A.equal(map.get('acc_settings_v7__before_fleet_v1'),'{"ppeRecords":[{"id":"KEEP"}]}');delete global.localStorage;});
test('brak miejsca na kopię ratunkową blokuje nadpisanie starego cache',()=>{const map=new Map([['acc_settings_v7','ORIGINAL']]);global.localStorage={getItem:k=>map.get(k)??null,setItem:(k,v)=>{if(k.includes('__before'))throw Error('quota');map.set(k,v);}};A.equal(safeCacheSet('acc_settings_v7',{changed:true}),false);A.equal(map.get('acc_settings_v7'),'ORIGINAL');delete global.localStorage;});
