"use client";
import React, { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { AlertTriangle, Archive, CalendarDays, Car, CheckCircle2, ChevronRight, Download, Gauge, LogOut, Plus, Printer, RefreshCw, Search, ShieldCheck, UserRound, Users, Wrench } from "lucide-react";
import { api, downloadText } from "@/lib/fleet/client";
import { costTotals, csvCell, dayDifference, effectiveEventMileage, localToday, planAlert, vehicleAlerts } from "@/lib/fleet/domain";
import { fleetLocale, tr } from "@/lib/fleet/i18n";
import { printVehicle } from "@/lib/fleet/print";
import type { FleetFile, FleetMember, PlanAlert, Vehicle, VehicleDetail } from "@/lib/fleet/types";
import { CommandModal, MembersModal, type ModalSpec } from "./forms";
import { Badge, Btn, DateText, ErrorBanner, errorCode, FileTiles, FileViewer, Info, Input, num, Panel, Pick, PrivateImage } from "./common";

interface Props { lang:string;user:string;people:string[];projects:string[] }
const stale=(v:Vehicle)=>v.data.mileage==null||!v.data.mileageDate||dayDifference(v.data.mileageDate)<-30;
const needsAttention=(v:Vehicle)=>!v.data.archived&&(v.data.openDefects>0||stale(v)||!v.data.plans.some(p=>!p.archived)||vehicleAlerts(v).some(a=>a.severity!=="ok"));
const alertTone=(s:PlanAlert["severity"]):"red"|"amber"|"green"=>s==="overdue"?"red":s==="ok"?"green":"amber";

export default function FleetPage({lang,user,people,projects}:Props) {
  const [member,setMember]=useState<FleetMember|null>(null),[authLoading,setAuthLoading]=useState(true),[authError,setAuthError]=useState("");
  const [name,setName]=useState(user),[pin,setPin]=useState("");
  const [vehicles,setVehicles]=useState<Vehicle[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState("");
  const [selected,setSelected]=useState(""),[detail,setDetail]=useState<VehicleDetail|null>(null),[detailLoading,setDetailLoading]=useState(false);
  const [query,setQuery]=useState(""),[filter,setFilter]=useState("active"),[status,setStatus]=useState(""),[driver,setDriver]=useState(""),[category,setCategory]=useState("");
  const [view,setView]=useState("dashboard"),[tab,setTab]=useState("overview"),[historyType,setHistoryType]=useState("");
  const [modal,setModal]=useState<ModalSpec|null>(null),[showMembers,setShowMembers]=useState(false),[file,setFile]=useState<FleetFile|null>(null),[toast,setToast]=useState("");
  const [actionBusy,setActionBusy]=useState(false); const selectedRef=useRef(""); const admin=member?.role==="admin";

  const checkAuth=useCallback(async()=>{setAuthLoading(true);setAuthError("");try{const r=await api<{member:FleetMember}>("session");setMember(r.member);}catch(e){const code=errorCode(e);if(code!=="LOGIN_REQUIRED")setAuthError(code);setMember(null);}finally{setAuthLoading(false);}},[]);
  useEffect(()=>{void checkAuth();},[checkAuth]);
  const loadVehicles=useCallback(async()=>{setLoading(true);setError("");try{const r=await api<{vehicles:Vehicle[]}>("vehicles");setVehicles(r.vehicles);}catch(e){setError(errorCode(e));}finally{setLoading(false);}},[]);
  useEffect(()=>{if(member)void loadVehicles();},[member,loadVehicles]);
  useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(""),5000);return()=>clearTimeout(t);},[toast]);
  const loadDetail=useCallback(async(id:string,propagate=false)=>{selectedRef.current=id;setSelected(id);setDetailLoading(true);setError("");try{const r=await api<VehicleDetail>(`vehicles/${id}`);if(selectedRef.current===id)setDetail(r);}catch(e){if(selectedRef.current===id)setError(errorCode(e));if(propagate)throw e;}finally{if(selectedRef.current===id)setDetailLoading(false);}},[]);
  async function signIn(e:React.FormEvent){e.preventDefault();setAuthLoading(true);setAuthError("");try{const r=await api<{member:FleetMember}>("login",{name,pin});setMember(r.member);setPin("");}catch(e){setAuthError(errorCode(e));}finally{setAuthLoading(false);}}
  async function signOut(){try{await api("logout",{});setMember(null);setVehicles([]);setSelected("");setDetail(null);setModal(null);}catch(e){setError(errorCode(e));}}
  function saved(d:VehicleDetail){setDetail(d);selectedRef.current=d.vehicle.id;setSelected(d.vehicle.id);setVehicles(prev=>[d.vehicle,...prev.filter(v=>v.id!==d.vehicle.id)]);setModal(null);setToast(tr(lang,"saved"));if(d.vehicle.data.archived)setFilter("archived");else if(filter==="archived")setFilter("active");}
  async function refresh(){await loadVehicles();if(selectedRef.current)await loadDetail(selectedRef.current);}
  async function quick(type:string,payload:Record<string,unknown>){if(!detail||actionBusy)return;setActionBusy(true);setError("");try{const d=await api<VehicleDetail>("commands",{commandId:crypto.randomUUID(),vehicleId:detail.vehicle.id,expectedVersion:detail.vehicle.version,type,payload,fileIds:[]});saved(d);}catch(e){setError(errorCode(e));}finally{setActionBusy(false);}}
  const filtered=useMemo(()=>vehicles.filter(v=>{
    const d=v.data; const hay=[d.plate,d.name,d.make,d.model,d.vin,d.driver,d.project,d.location,d.company].join(" ").toLocaleLowerCase();
    return hay.includes(query.trim().toLocaleLowerCase())&&(!status||(status==="immobilized"?["service","out_of_service"].includes(d.status):d.status===status))&&(!driver||d.driver===driver)&&(!category||d.category===category)&&
      (filter==="archived"?d.archived:!d.archived&&(filter!=="attention"||needsAttention(v))&&(filter!=="noDriver"||!d.driver)&&(filter!=="noMileage"||stale(v)));
  }).sort((a,b)=>Number(needsAttention(b))-Number(needsAttention(a))||a.data.plate.localeCompare(b.data.plate)),[vehicles,query,status,driver,category,filter]);
  const active=vehicles.filter(v=>!v.data.archived);
  const alerts=useMemo(()=>active.flatMap(v=>vehicleAlerts(v).map(a=>({...a,vehicle:v}))).sort((a,b)=>({overdue:0,soon:1,missing:2,ok:3}[a.severity]-{overdue:0,soon:1,missing:2,ok:3}[b.severity])||((a.days??99999)-(b.days??99999))),[vehicles]); // eslint-disable-line react-hooks/exhaustive-deps
  function exportCsv(){const keys=["plate","make","model","vin","driver","project","mileage","mileageDate","status"] as const;const rows=[keys.map(k=>csvCell(tr(lang,k))).join(";"),...filtered.map(v=>keys.map(k=>csvCell(k==="status"?tr(lang,v.data.status):v.data[k])).join(";"))];downloadText(`ACC-BAU-pojazdy-${localToday()}.csv`,"\uFEFF"+rows.join("\r\n"),"text/csv;charset=utf-8");}
  const shownDetail=detail?.vehicle.id===selected?detail:null;
  if(!member) return <Panel className="mx-auto max-w-2xl"><div className="mb-4 inline-flex rounded-2xl bg-orange-100 p-3 text-orange-700"><Car className="h-7 w-7"/></div><h2 className="text-2xl font-black">{tr(lang,authError==="SETUP_REQUIRED"||authError==="MIGRATION_REQUIRED"||authError==="SECRET_TOO_SHORT"?"setupTitle":"fleetLogin")}</h2>
    {["SETUP_REQUIRED","MIGRATION_REQUIRED","SECRET_TOO_SHORT"].includes(authError)?<><p className="my-4 leading-relaxed text-zinc-600">{tr(lang,"setupText")}</p><ErrorBanner lang={lang} error={authError}/><Btn onClick={checkAuth}>{tr(lang,"retry")}</Btn></>:<form onSubmit={signIn} className="mt-4 space-y-4"><p className="text-sm leading-relaxed text-zinc-600">{tr(lang,"loginHint")}</p><ErrorBanner lang={lang} error={authError}/><datalist id="fleet-login-names">{Array.from(new Set(people)).map(p=><option key={p} value={p}/>)}</datalist><Input label={tr(lang,"loginName")} required value={name} list="fleet-login-names" onChange={e=>setName(e.target.value)} autoComplete="username"/><Input label={tr(lang,"pin")} required type="password" value={pin} onChange={e=>setPin(e.target.value)} autoComplete="current-password"/><Btn type="submit" tone="primary" disabled={authLoading}>{tr(lang,authLoading?"loading":"enter")}</Btn></form>}
    <p className="mt-5 border-t pt-4 text-xs text-zinc-500">{tr(lang,"retained")}</p></Panel>;

  return <div className="space-y-5">
    <Panel><div className="flex flex-col justify-between gap-4 xl:flex-row"><div><div className="mb-2 text-xs font-black tracking-widest text-orange-600">ACC BAU • FLEET</div><h2 className="text-3xl font-black tracking-tight">{tr(lang,"title")}</h2><p className="mt-1 text-sm text-zinc-500">{tr(lang,"subtitle")}</p></div><div className="flex flex-wrap items-start gap-2"><Btn onClick={refresh} disabled={loading||detailLoading}><RefreshCw className={`h-4 w-4 ${loading?"animate-spin":""}`}/>{tr(lang,"refresh")}</Btn>{admin&&<><Btn onClick={()=>setShowMembers(true)}><Users className="h-4 w-4"/>{tr(lang,"members")}</Btn><Btn tone="primary" onClick={()=>setModal({type:"create"})}><Plus className="h-4 w-4"/>{tr(lang,"addVehicle")}</Btn></>}<Btn onClick={signOut} title={tr(lang,"logout")} aria-label={tr(lang,"logout")}><LogOut className="h-4 w-4"/></Btn></div></div><div className="mt-4 flex flex-wrap items-center gap-2 border-t pt-3 text-xs text-zinc-500"><ShieldCheck className="h-4 w-4 text-emerald-600"/><b>{member.name} • {tr(lang,member.role)}</b><span>— {tr(lang,"retained")}</span></div></Panel>
    <ErrorBanner lang={lang} error={error}/>{toast&&<div role="status" className="flex gap-2 rounded-2xl border border-emerald-200 bg-emerald-50 p-3 text-sm font-bold text-emerald-800"><CheckCircle2 className="h-5 w-5"/>{toast}</div>}
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[
      {key:"fleetCount",value:active.length,icon:Car,click:()=>{setFilter("active");setView("dashboard");}},
      {key:"deadlines",value:alerts.filter(a=>a.severity!=="ok").length,icon:CalendarDays,click:()=>setView("calendar")},
      {key:"defects",value:active.reduce((n,v)=>n+v.data.openDefects,0),icon:AlertTriangle,click:()=>{setFilter("attention");setView("dashboard");}},
      {key:"immobilized",value:active.filter(v=>["service","out_of_service"].includes(v.data.status)).length,icon:Wrench,click:()=>{setFilter("active");setStatus("immobilized");setView("dashboard");}},
    ].map(s=><button key={s.key} onClick={s.click} className="flex items-center gap-4 rounded-3xl border border-zinc-200 bg-white p-5 text-left shadow-sm transition hover:-translate-y-0.5"><span className={`rounded-2xl p-3 ${s.key!=="fleetCount"&&s.value?"bg-orange-50 text-orange-700":"bg-zinc-100 text-zinc-600"}`}><s.icon className="h-6 w-6"/></span><span><span className="block text-xs font-bold text-zinc-500">{tr(lang,s.key)}</span><strong className="text-3xl">{s.value}</strong></span></button>)}</div>
    <div className="flex flex-wrap gap-2"><Btn tone={view==="dashboard"?"primary":"light"} onClick={()=>setView("dashboard")}><Car className="h-4 w-4"/>{tr(lang,"dashboard")}</Btn><Btn tone={view==="calendar"?"primary":"light"} onClick={()=>setView("calendar")}><CalendarDays className="h-4 w-4"/>{tr(lang,"calendar")}</Btn>{admin&&<Btn onClick={exportCsv}><Download className="h-4 w-4"/>{tr(lang,"exportCsv")}</Btn>}</div>
    {view==="calendar"?<Panel><h3 className="text-xl font-black">{tr(lang,"calendar")}</h3><p className="mt-2 text-sm text-zinc-500">{tr(lang,"firstDue")} {tr(lang,"calendarHint")}</p>{active.filter(v=>!v.data.plans.some(p=>!p.archived)).map(v=><button key={v.id} onClick={()=>{setView("dashboard");setTab("plans");void loadDetail(v.id);}} className="mt-3 block w-full rounded-xl border border-amber-200 bg-amber-50 p-3 text-left text-sm"><b>{v.data.plate}</b> — {tr(lang,"noPlans")}</button>)}<div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b text-xs text-zinc-500"><tr>{["vehicles","label","dueDate","dueMileage","status"].map(k=><th className="p-3" key={k}>{tr(lang,k)}</th>)}</tr></thead><tbody>{alerts.map(a=><tr key={`${a.vehicle.id}-${a.plan.id}`} className="border-b"><td className="p-3"><button className="font-black text-orange-700" onClick={()=>{setView("dashboard");setTab("plans");void loadDetail(a.vehicle.id);}}>{a.vehicle.data.plate}</button><div className="text-xs text-zinc-500">{a.vehicle.data.driver||"—"}</div></td><td className="p-3">{a.plan.label}</td><td className="p-3 whitespace-nowrap"><DateText date={a.plan.dueDate} lang={lang}/></td><td className="p-3 whitespace-nowrap">{num(a.plan.dueMileage,lang)}{a.km!=null&&<div className="text-xs text-zinc-500">{tr(lang,"remaining")}: {num(a.km,lang)} km</div>}</td><td className="p-3"><Badge tone={alertTone(a.severity)}>{tr(lang,a.severity)}</Badge></td></tr>)}</tbody></table></div></Panel>:
    <div className="grid items-start gap-5 xl:grid-cols-[minmax(300px,0.85fr)_minmax(0,1.5fr)]">
      <Panel><div className="flex items-center gap-2"><Search className="h-5 w-5 text-zinc-400"/><input aria-label={tr(lang,"search")} placeholder={tr(lang,"search")} value={query} onChange={e=>setQuery(e.target.value)} className="min-w-0 flex-1 rounded-xl border px-3 py-2.5 text-sm outline-none focus:border-orange-500"/></div><div className="mt-3 flex flex-wrap gap-1.5">{["active","attention","noDriver","noMileage","archived"].map(f=><button key={f} onClick={()=>setFilter(f)} className={`rounded-full px-3 py-1.5 text-xs font-bold ${filter===f?"bg-zinc-900 text-white":"bg-zinc-100 text-zinc-600"}`}>{tr(lang,f)}</button>)}</div>
        <div className="mt-4 grid gap-2 sm:grid-cols-2"><Pick label={tr(lang,"status")} value={status} onChange={e=>setStatus(e.target.value)} options={[{value:"",label:tr(lang,"all")},...["immobilized","available","in_use","service","out_of_service","sold"].map(value=>({value,label:tr(lang,value)}))]}/><Pick label={tr(lang,"driver")} value={driver} onChange={e=>setDriver(e.target.value)} options={[{value:"",label:tr(lang,"all")},...Array.from(new Set(vehicles.map(v=>v.data.driver).filter(Boolean))).sort().map(value=>({value,label:value}))]}/><Pick label={tr(lang,"category")} value={category} onChange={e=>setCategory(e.target.value)} options={[{value:"",label:tr(lang,"all")},...["car","van","truck","trailer","machine","other"].map(value=>({value,label:tr(lang,value)}))]}/></div>
        <div className="mt-4 space-y-3">{loading&&!vehicles.length&&<p className="py-10 text-center text-sm text-zinc-500">{tr(lang,"loading")}</p>}{!loading&&!filtered.length&&<p className="rounded-2xl border border-dashed p-8 text-center text-sm text-zinc-500">{tr(lang,vehicles.length?"empty":"firstVehicle")}</p>}
          {filtered.map(v=><button key={v.id} onClick={()=>{void loadDetail(v.id);}} className={`w-full rounded-2xl border p-3 text-left transition hover:border-orange-300 ${selected===v.id?"border-orange-400 bg-orange-50/60 ring-1 ring-orange-200":"border-zinc-200 bg-white"}`}><div className="flex gap-3"><PrivateImage id={v.data.coverFileId} alt={v.data.plate} className="h-20 w-24 shrink-0 rounded-xl"/><div className="min-w-0 flex-1"><div className="flex items-center justify-between"><b className="text-lg tracking-wide">{v.data.plate}</b><ChevronRight className="h-4 w-4 text-zinc-400"/></div><div className="truncate text-sm text-zinc-600">{v.data.make} {v.data.model}</div><div className="mt-1 flex flex-wrap gap-1"><Badge tone={v.data.status==="out_of_service"?"red":"neutral"}>{tr(lang,v.data.archived?"archived":v.data.status)}</Badge>{needsAttention(v)&&<Badge tone="amber">{tr(lang,"attention")}</Badge>}</div></div></div><div className="mt-3 grid grid-cols-2 gap-2 border-t pt-2 text-xs text-zinc-600"><span className="flex items-center gap-1"><UserRound className="h-3.5 w-3.5"/>{v.data.driver||tr(lang,"noDriver")}</span><span className="text-right"><Gauge className="mr-1 inline h-3.5 w-3.5"/>{num(v.data.mileage,lang)} km</span></div></button>)}
        </div>
      </Panel>
      <div className="min-w-0 space-y-5">{detailLoading?<Panel><p className="py-12 text-center text-zinc-500">{tr(lang,"loading")}</p></Panel>:!shownDetail?<Panel><div className="py-20 text-center text-zinc-400"><Car className="mx-auto mb-4 h-16 w-16"/><p>{tr(lang,"choose")}</p></div></Panel>:<>
        <Panel><div className="flex flex-col gap-4 sm:flex-row"><PrivateImage id={shownDetail.vehicle.data.coverFileId} alt={shownDetail.vehicle.data.plate} className="h-40 w-full rounded-2xl sm:w-48"/><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="text-3xl font-black tracking-wide">{shownDetail.vehicle.data.plate}</h3><Badge tone={shownDetail.vehicle.data.status==="out_of_service"?"red":"neutral"}>{tr(lang,shownDetail.vehicle.data.archived?"archived":shownDetail.vehicle.data.status)}</Badge></div><p className="mt-1 text-lg text-zinc-600">{shownDetail.vehicle.data.make} {shownDetail.vehicle.data.model}</p><p className="mt-1 text-xs text-zinc-400">{shownDetail.vehicle.data.name} • {shownDetail.vehicle.data.vin||"VIN —"}</p><div className="mt-3 grid grid-cols-2 gap-3"><Info label={tr(lang,"driver")} value={shownDetail.vehicle.data.driver}/><Info label={tr(lang,"mileage")} value={`${num(shownDetail.vehicle.data.mileage,lang)} km`}/></div></div></div>
          <div className="mt-3 text-xs text-zinc-500">{tr(lang,"mileageDate")}: <DateText date={shownDetail.vehicle.data.mileageDate} lang={lang}/></div>{stale(shownDetail.vehicle)&&<div className="mt-3 rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs font-bold text-amber-800">{tr(lang,shownDetail.vehicle.data.mileage==null?"error_MILEAGE_REQUIRED":"lastMileageOld")}</div>}
          <div className="mt-4 flex flex-wrap gap-2">{!shownDetail.vehicle.data.archived&&<><Btn tone="primary" onClick={()=>setModal({type:"mileage"})}><Gauge className="h-4 w-4"/>{tr(lang,"addMileage")}</Btn>{admin&&<><Btn onClick={()=>setModal({type:"service"})}><Wrench className="h-4 w-4"/>{tr(lang,"newService")}</Btn><Btn onClick={()=>setModal({type:"assignment"})}><UserRound className="h-4 w-4"/>{tr(lang,"assign")}</Btn></>}<Btn tone="danger" onClick={()=>setModal({type:"defect"})}><AlertTriangle className="h-4 w-4"/>{tr(lang,"defect")}</Btn></>}
          {admin&&<><Btn onClick={()=>{if(!printVehicle(shownDetail,lang))setError("POPUP_BLOCKED");}}><Printer className="h-4 w-4"/>{tr(lang,"print")}</Btn><Btn onClick={()=>downloadText(`ACC-BAU-${shownDetail.vehicle.data.plate}-${localToday()}.json`,JSON.stringify({exportedAt:new Date().toISOString(),format:"acc-fleet-v1",includesFileContents:false,...shownDetail},null,2),"application/json")}>{tr(lang,"exportJson")}</Btn></>}</div>
          <div className="mt-5 flex flex-wrap gap-1 border-t pt-3">{["overview","plans","history","documents"].map(t=><button key={t} onClick={()=>setTab(t)} className={`rounded-xl px-3 py-2 text-xs font-black ${tab===t?"bg-zinc-900 text-white":"text-zinc-500 hover:bg-zinc-100"}`}>{tr(lang,t)}</button>)}</div>
        </Panel>
        {tab==="overview"&&<Panel><div className="mb-4 flex flex-wrap justify-between gap-2"><h4 className="text-lg font-black">{tr(lang,"overview")}</h4>{admin&&<div className="flex gap-2">{!shownDetail.vehicle.data.archived&&<Btn onClick={()=>setModal({type:"update"})}>{tr(lang,"editVehicle")}</Btn>}<Btn onClick={()=>setModal({type:shownDetail.vehicle.data.archived?"restore":"archive"})}><Archive className="h-4 w-4"/>{tr(lang,shownDetail.vehicle.data.archived?"restore":"archive")}</Btn></div>}</div><dl className="grid gap-3 sm:grid-cols-2">{["company","project","location","year","country","fuel","transmission","firstRegistration","engine","power","maxMass","payload","seats","tyreSize","insurer","assistancePhone",...(admin?["ownership","purchaseDate","purchasePrice","purchaseCurrency","leasingUntil","policyNumber"]:[])].map(k=><Info key={k} label={tr(lang,k)} value={shownDetail.vehicle.data[k as keyof typeof shownDetail.vehicle.data] as string}/>)}</dl>{shownDetail.vehicle.data.notes&&<p className="mt-4 whitespace-pre-wrap rounded-xl bg-zinc-50 p-3 text-sm">{shownDetail.vehicle.data.notes}</p>}{admin&&<div className="mt-5 border-t pt-4"><h5 className="font-black">{tr(lang,"costSummary")}</h5><div className="mt-3 flex flex-wrap gap-2">{Object.entries(costTotals(shownDetail.events)).map(([key,total])=><Badge key={key}>{total.toLocaleString(fleetLocale(lang),{minimumFractionDigits:2,maximumFractionDigits:2})} {key.split(" ")[0]} {tr(lang,key.split(" ")[1])}</Badge>)}</div><p className="mt-2 text-xs text-zinc-500">{tr(lang,"costHint")}</p></div>}</Panel>}
        {tab==="plans"&&<Panel><div className="flex flex-wrap items-center justify-between gap-2"><h4 className="text-lg font-black">{tr(lang,"plans")}</h4>{admin&&!shownDetail.vehicle.data.archived&&<Btn tone="primary" onClick={()=>setModal({type:"plan_add"})}><Plus className="h-4 w-4"/>{tr(lang,"addPlan")}</Btn>}</div><p className="mt-2 text-xs text-zinc-500">{tr(lang,"firstDue")}</p><div className="mt-4 space-y-3">{!shownDetail.vehicle.data.plans.length&&<p className="rounded-xl bg-amber-50 p-4 text-sm text-amber-900">{tr(lang,"noPlans")}</p>}{shownDetail.vehicle.data.plans.map(p=>{const a=planAlert(p,shownDetail.vehicle.data.mileage);return <div key={p.id} className={`rounded-2xl border p-4 ${p.archived?"border-zinc-200 bg-zinc-50 opacity-70":a.severity==="overdue"?"border-red-200 bg-red-50/40":"border-zinc-200"}`}><div className="flex flex-wrap justify-between gap-2"><h5 className="font-black">{p.label}</h5><Badge tone={p.archived?"neutral":alertTone(a.severity)}>{tr(lang,p.archived?"archived":a.severity)}</Badge></div><div className="mt-3 grid grid-cols-2 gap-3 text-sm"><Info label={tr(lang,"dueDate")} value={<DateText date={p.dueDate} lang={lang}/>}/><Info label={tr(lang,"dueMileage")} value={num(p.dueMileage,lang)}/></div><div className="mt-2 flex flex-wrap gap-x-4 text-xs text-zinc-500">{a.days!=null&&<span>{tr(lang,"remaining")}: {a.days} {tr(lang,"days")}</span>}{a.km!=null&&<span>{tr(lang,"remaining")}: {num(a.km,lang)} km</span>}{p.lastDoneDate&&<span>{tr(lang,"lastDone")}: <DateText date={p.lastDoneDate} lang={lang}/></span>}</div>{p.notes&&<p className="mt-2 whitespace-pre-wrap text-xs text-zinc-500">{p.notes}</p>}{admin&&!p.archived&&!shownDetail.vehicle.data.archived&&<div className="mt-3 flex flex-wrap gap-2"><Btn onClick={()=>setModal({type:"service",plan:p})}>{tr(lang,"newService")}</Btn><Btn onClick={()=>setModal({type:"plan_update",plan:p})}>{tr(lang,"editPlan")}</Btn><Btn onClick={()=>setModal({type:"plan_archive",plan:p})}>{tr(lang,"planArchive")}</Btn></div>}</div>;})}</div></Panel>}
        {tab==="history"&&<Panel><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><h4 className="text-lg font-black">{tr(lang,"history")}</h4><Pick label={tr(lang,"kind")} value={historyType} onChange={e=>setHistoryType(e.target.value)} options={[{value:"",label:tr(lang,"all")},...["service","repair","inspection","mileage","assignment","defect","mileage_correction"].map(value=>({value,label:tr(lang,value)}))]}/></div><div className="space-y-3">{shownDetail.events.filter(e=>!historyType||e.kind===historyType).map(e=>{const reading=effectiveEventMileage(e,shownDetail.events);const corrected=reading!=null&&reading!==e.data.mileage;const closed=shownDetail.events.some(r=>r.kind==="defect_closed"&&r.data.resolvedId===e.id);return <article key={e.id} className="rounded-2xl border border-zinc-200 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><Badge tone={e.kind==="defect"&&!closed?"red":"neutral"}>{tr(lang,e.kind)}{closed?" ✓":""}</Badge><span className="text-xs text-zinc-500"><DateText date={e.happened_on} lang={lang}/></span></div>{e.data.title&&<h5 className="mt-2 font-bold">{e.data.title}</h5>}{e.data.from||e.data.to?<p className="mt-1 text-sm font-bold text-orange-700">{e.data.from||"—"} → {e.data.to||"—"}</p>:null}{e.data.notes&&<p className="mt-2 whitespace-pre-wrap text-sm text-zinc-600">{e.data.notes}</p>}{e.data.reason&&<p className="mt-2 text-sm"><b>{tr(lang,"reason")}:</b> {e.data.reason}</p>}{e.kind==="mileage_correction"&&<p className="mt-2 text-sm"><b>{tr(lang,"correctedMileage")}:</b> {num(e.data.correctedMileage,lang)} km</p>}
          <div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-xs text-zinc-500">{e.data.mileage!=null&&<span>{tr(lang,"mileage")}: <b>{num(reading,lang)} km</b>{corrected&&<span> ({tr(lang,"original")}: {num(e.data.mileage,lang)} km)</span>}</span>}{e.data.workshop&&<span>{tr(lang,"workshop")}: {e.data.workshop}</span>}{admin&&e.data.cost!=null&&<span><b>{num(e.data.cost,lang)} {e.data.currency} {tr(lang,e.data.costBasis||"gross")}</b></span>}{admin&&e.data.invoiceNumber&&<span>{tr(lang,"invoiceNumber")}: {e.data.invoiceNumber}</span>}</div>
          {e.data.plan&&<p className="mt-2 text-xs text-zinc-500">{tr(lang,"dueDate")}: {e.data.previousPlan?.dueDate||"—"} → {e.data.plan.dueDate||"—"} • {tr(lang,"dueMileage")}: {num(e.data.previousPlan?.dueMileage,lang)} → {num(e.data.plan.dueMileage,lang)}</p>}
          {e.data.completedPlans?.length ? <p className="mt-2 text-xs text-zinc-500">{tr(lang,"completedPlans")}: {e.data.completedPlans.map(id=>shownDetail.vehicle.data.plans.find(p=>p.id===id)?.label||id).join(", ")}</p>:null}
          {admin&&e.data.changedFields&&<details className="mt-3 text-xs"><summary className="cursor-pointer font-bold">{tr(lang,"updated")}</summary><div className="mt-2 space-y-1">{e.data.changedFields.map(k=><p key={k}><b>{tr(lang,k)}:</b> {String((e.data.before as Record<string,unknown>)?.[k]??"—")} → {String((e.data.after as Record<string,unknown>)?.[k]??"—")}</p>)}</div></details>}
          <div className="mt-3"><FileTiles files={shownDetail.files.filter(f=>f.event_id===e.id||shownDetail.events.some(a=>a.id===f.event_id&&a.data.relatedEventId===e.id))} lang={lang} onView={setFile}/></div><div className="mt-3 flex flex-wrap items-center justify-between gap-2 border-t pt-2"><span className="text-[11px] text-zinc-400">{tr(lang,"by")}: {e.created_by} • <DateText date={e.created_at} lang={lang}/></span>{admin&&!shownDetail.vehicle.data.archived&&<div className="flex flex-wrap gap-2">{["service","repair","inspection","assignment","defect"].includes(e.kind)&&<Btn onClick={()=>setModal({type:"document_attach",event:e})}>{tr(lang,"attachToRecord")}</Btn>}{e.data.mileage!=null&&e.kind!=="mileage_correction"&&<button onClick={()=>setModal({type:"mileage_correction",event:e})} className="text-xs font-bold text-orange-700">{tr(lang,"correctMileage")}</button>}{e.kind==="defect"&&!closed&&<Btn onClick={()=>setModal({type:"defect_close",event:e})}>{tr(lang,"defectClose")}</Btn>}</div>}</div></article>;})}</div></Panel>}
        {tab==="documents"&&<Panel><div className="mb-4 flex flex-wrap items-center justify-between gap-2"><h4 className="text-lg font-black">{tr(lang,"documents")}</h4>{!shownDetail.vehicle.data.archived&&<Btn tone="primary" onClick={()=>setModal({type:"document"})}><Plus className="h-4 w-4"/>{tr(lang,"newDocuments")}</Btn>}</div><p className="mb-4 text-xs text-zinc-500">{tr(lang,"fileHint")}</p>{!shownDetail.files.length&&<p className="p-8 text-center text-sm text-zinc-500">{tr(lang,"noFiles")}</p>}<div className="grid gap-3 sm:grid-cols-2">{shownDetail.files.map(f=><div key={f.id} className="overflow-hidden rounded-2xl border border-zinc-200">{f.mime.startsWith("image/")&&<button onClick={()=>setFile(f)} className="w-full"><PrivateImage id={f.id} alt={f.name} className="h-40 w-full"/></button>}<div className="space-y-2 p-3"><Badge>{tr(lang,f.category)}</Badge><p className="break-words text-sm font-bold">{f.name}</p><p className="text-xs text-zinc-500">{(f.size/1024/1024).toFixed(2)} MB • <DateText date={f.created_at} lang={lang}/></p>{!f.event_id&&<p className="text-xs text-amber-700">{tr(lang,"unlinked")}</p>}<div className="flex flex-wrap gap-2"><Btn onClick={()=>setFile(f)}>{tr(lang,"preview")}</Btn>{admin&&f.category==="photo"&&!shownDetail.vehicle.data.archived&&shownDetail.vehicle.data.coverFileId!==f.id&&<Btn disabled={actionBusy} onClick={()=>quick("cover",{id:f.id})}>{tr(lang,"cover")}</Btn>}</div></div></div>)}</div></Panel>}
      </>}</div>
    </div>}
    {modal&&<CommandModal key={`${modal.type}-${modal.event?.id||modal.plan?.id||""}`} spec={modal} detail={modal.type==="create"?null:shownDetail} lang={lang} member={member} people={Array.from(new Set([...people,...vehicles.map(v=>v.data.driver).filter(Boolean),member.name]))} projects={projects} onClose={()=>setModal(null)} onSaved={saved} onRefresh={async()=>{if(selected)await loadDetail(selected,true);}}/>}
    {showMembers&&<MembersModal lang={lang} people={people} current={member} onClose={()=>setShowMembers(false)} onSessionExpired={()=>{setShowMembers(false);setMember(null);}}/>}
    {file&&<FileViewer file={file} lang={lang} onClose={()=>setFile(null)}/>}
  </div>;
}
